### PR TITLE
Various small fixes 

### PR DESCRIPTION
**Pull request by anka-213**
Three fixes that prevented code I was working on from being unpacked

* fix: Make isIIFE match what it claims to match
    More specifically:

      !function(){...}()

    wasn't matched, only

      !function(){...}

    which isn't an IIFE

* Fix: Remove buggy and redundant transform
    
   No need to remove import `foo as foo`. The desired behaviour happens automatically and other code expects the `local` field (`as foo`) to exist to not crash.
    
      import { foo as foo } to import { foo }

    will automatically be printed as

      import { foo } to import { foo }

    without this transform

* feat: Allow re-exports from modules in Webpack5
    If a module re-exports values from another module,
    Webpack5 would export them as
    
        var r = n(645); n.d(t, { foo: () => r.foo })
    
    so this adds member-expressions to the expected possible values

* feat: Allow Arrow functions in module definitions
    
    Example:

      (self.webpackChunk_N_E=self.webpackChunk_N_E ||
           []).push([[888],{2189: (e,t,n) => {...} }

### CODE REVIEW

**Comment by pionxzh** [comment]
Can you help to update the test cases accordingly?

**Comment by anka-213** [comment]
Will do! I was apparently wrong in my assumption regarding the `foo as foo`. I thought I had tested it, but apparently my tests didn't cover those cases.

**Comment by pionxzh** [comment]
I want to know more about the "buggy" part of `foo as foo` transformation. What would be the real-world issue? Semantic changes or wakaru throwing error?

**Comment by anka-213** [comment]
wakaru throwing error. More specifically it was when running `wakaru all somefile.js`. I got crashes from two of the transforms. Let me try to reproduce it.

**Comment by anka-213** [comment]
These are the lines that the crash originated from:
https://github.com/benjamn/ast-types/blob/v0.16.1/src/scope.ts#L256-L258

As you can see it assumes that one of `local`, `name` or `id` exists on the binding, but if you call `j.importSpecifier` with only one argument none of them is set. When I tried using astexplorer, it does set `local` even if it's only a single value with no `as`.

**Comment by pionxzh** [comment]
Do you have a short reproduction? We can also patch `ast-types` by ourself if this is indeed a bug from `ast-types`.

**Comment by anka-213** [comment]
I unfortunately haven't extracted a short reproduction yet, but I have found a simple fix. Constructing a new identifier and using it for both arguments does produce the desired behavior.

I'll see if I can make a short reproduction as well.

**Comment by anka-213** [comment]
I also removed another change that caused test failures. Sorry for not running the tests before sending a PR

**Comment by pionxzh** [comment]
Don't worry.

I also updated another iife matching that should be corrected.

**Comment by pionxzh** [comment]
one more thing. Please help to update the commit message from "Fix" to fix. The Changelog tool will be mad about it 🤣

**Comment by anka-213** [comment]
Haha, done! I also restored the isIIFE fix now that your commit fixed the test failure.

**Comment by anka-213** [comment]
Here's a minimal reproduction of the bug. It's a combination of the first test case for `un-import-rename` and the first test case for `un-optional-chaining`, but it works with any combination of `un-import-rename` and something that uses `@wakaru/ast-utils/scope`.

```typescript
import { foo as a, bar as b, code } from '_';

console.log(a, b, code);

var _a;
(_a = a) === null || _a === void 0 ? void 0 : _a.b;
```

**Comment by pionxzh** [comment]
You can inline combined rules if there is only one test case, or declare it as a variable.

https://github.com/pionxzh/wakaru/blob/e099371b653c42f9ce975a51cfd6230f1294abb8/packages/unminify/src/transformations/__tests__/un-default-parameter.spec.ts#L5

https://github.com/pionxzh/wakaru/blob/e099371b653c42f9ce975a51cfd6230f1294abb8/packages/unminify/src/transformations/__tests__/un-nullish-coalescing.spec.ts#L122-L125

**Review by pionxzh — APPROVED** [review]

**Comment by pionxzh** [comment]
Thanks for fixing some many issues. 👍

**Pull request merged**
